on:
  issues:
    types: [opened, labeled]
jobs:
  setup:
    if: ${{ github.event.issue.labels[0].name == 'delete_submission' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      - uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/04_delete_submission.yml
          
      - run: node ./js/delete_submission.js >> $GITHUB_OUTPUT
        id: delete
        env:
          USER_ID: ${{ github.event.sender.id }}
          
      - run: |
            git config user.email "quinny898+sst@gmail.com"
            git config user.name "Smartspacer Plugin Repository Bot"
            git add plugins.json
            git diff-index --quiet HEAD || git commit -m "Deleted plugin"
        
      - run: git push
        if: "${{ steps.delete.outputs.result == 'true' }}"
      
      - name: Read comment.txt
        id: comment
        uses: juliangruber/read-file-action@v1
        with:
          path: ./comment.txt
          
      - uses: OSDKDev/unlock-issues@v1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - uses: peter-evans/close-issue@v1
        with:
          comment: "${{ steps.comment.outputs.content }}"
          
      - uses: OSDKDev/lock-issues@v1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
